#! /usr/bin/env python
import sys
import time
import socket

timeout = 600

services = sys.argv[1:]
start = time.time()
for service in services:
    host, port = service.split(':')
    while True:
        try:
            sock = socket.socket()
            sock.connect((host, int(port)))
            sock.close()
            print service, 'is up'
            break
        except socket.error as e:
            if time.time() - start >= timeout:
                print 'Timeout exceeded'
                sys.exit(1)

            print 'Waiting for', service
            time.sleep(3)
